/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "src/account_tests.ts" instead.
 */

#include <check.h>

#line 1 "src/account_tests.ts"

#line 3
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <time.h>
#include <limits.h>
#include "account.h"

/* Helper to create test accounts */
static account_t* create_test_account(void) {
    account_t* acc = account_create("testuser", "TestP@ss123", "test@example.com", "1990-01-01");
    if (acc == NULL) {
        ck_abort_msg("Failed to create test account");
    }
    return acc;
}

/*********************************************
 * Tests for account_validate_password
 *********************************************/

#line 23
/* Basic functionality tests */
START_TEST(valid_password_succeeds)
{
#line 25
    account_t* acc = create_test_account();
    ck_assert(account_validate_password(acc, "TestP@ss123"));
    account_free(acc);

}
END_TEST

START_TEST(invalid_password_fails)
{
#line 30
    account_t* acc = create_test_account();
    ck_assert(!account_validate_password(acc, "WrongP@ss123"));
    account_free(acc);

/* Edge cases */
}
END_TEST

START_TEST(null_parameters)
{
#line 36
    account_t* acc = create_test_account();
    
    /* Test NULL account */
    ck_assert(!account_validate_password(NULL, "TestP@ss123"));
    
    /* Test NULL password */
    ck_assert(!account_validate_password(acc, NULL));
    
    account_free(acc);

}
END_TEST

START_TEST(empty_password)
{
#line 47
    account_t* acc = create_test_account();
    
    /* Test empty password */
    ck_assert(!account_validate_password(acc, ""));
    
    account_free(acc);

}
END_TEST

START_TEST(very_long_password)
{
#line 55
    account_t* acc = create_test_account();
    
    /* Create a long password (longer than HASH_LENGTH) */
    char long_password[512];
    memset(long_password, 'A', 511);
    long_password[511] = '\0';
    
    /* Set a legitimate long password first */
    account_update_password(acc, "LongP@ssw0rd123");
    
    /* Validating with very long password should fail */
    ck_assert(!account_validate_password(acc, long_password));
    
    account_free(acc);

}
END_TEST

START_TEST(special_characters_in_password)
{
#line 71
    account_t* acc = create_test_account();
    
    /* Set password with special characters */
    char special_password[] = "P@ssw0rd!#$%^&*()_+";
    account_update_password(acc, special_password);
    
    /* Should validate correctly */
    ck_assert(account_validate_password(acc, special_password));
    
    account_free(acc);

}
END_TEST

START_TEST(account_with_no_password_hash)
{
#line 83
    account_t* acc = create_test_account();
    
    /* Clear the password hash */
    acc->password_hash[0] = '\0';
    
    /* Should fail validation with any password */
    ck_assert(!account_validate_password(acc, "TestP@ss123"));
    
    account_free(acc);

/* Account state tests */
}
END_TEST

START_TEST(banned_account_validation)
{
#line 95
    account_t* acc = create_test_account();
    
    /* Ban the account */
    time_t future_time = time(NULL) + 3600;
    account_set_unban_time(acc, future_time);
    
    /* Should fail validation even with correct password */
    ck_assert(!account_validate_password(acc, "TestP@ss123"));
    
    account_free(acc);

}
END_TEST

START_TEST(expired_account_validation)
{
#line 107
    account_t* acc = create_test_account();
    
    /* Expire the account */
    time_t past_time = time(NULL) - 3600;
    account_set_expiration_time(acc, past_time);
    
    /* Should fail validation even with correct password */
    ck_assert(!account_validate_password(acc, "TestP@ss123"));
    
    account_free(acc);

/*********************************************
 * Tests for account_update_password
 *********************************************/
}
END_TEST

#line 123
/* Basic functionality tests */
START_TEST(update_valid_password)
{
#line 125
    account_t* acc = create_test_account();
    ck_assert(account_update_password(acc, "NewP@ssw0rd!"));
    ck_assert(account_validate_password(acc, "NewP@ssw0rd!"));
    ck_assert(!account_validate_password(acc, "TestP@ss123"));
    account_free(acc);

/* Edge cases */
}
END_TEST

START_TEST(null_parameters_update)
{
#line 133
    account_t* acc = create_test_account();
    
    /* Test NULL account */
    ck_assert(!account_update_password(NULL, "NewP@ssw0rd!"));
    
    /* Test NULL password */
    ck_assert(!account_update_password(acc, NULL));
    
    account_free(acc);

}
END_TEST

START_TEST(empty_password_update)
{
#line 144
    account_t* acc = create_test_account();
    
    /* Test empty password */
    ck_assert(!account_update_password(acc, ""));
    
    account_free(acc);

}
END_TEST

START_TEST(very_long_password_update)
{
#line 152
    account_t* acc = create_test_account();
    
    /* Create a long password (longer than HASH_LENGTH) */
    char long_password[512];
    for (int i = 0; i < 510; i++) {
        if (i % 100 == 0) long_password[i] = '@';
        else if (i % 101 == 0) long_password[i] = '1';
        else long_password[i] = 'A' + (i % 26);
    }
    long_password[510] = '\0';
    
    /* Should be able to handle long password (though not recommended) */
    ck_assert(account_update_password(acc, long_password));
    ck_assert(account_validate_password(acc, long_password));
    
    account_free(acc);

}
END_TEST

START_TEST(special_characters_password_update)
{
#line 170
    account_t* acc = create_test_account();
    
    /* Set password with special characters */
    char special_password[] = "P@ssw0rd!#$%^&*()_+";
    
    ck_assert(account_update_password(acc, special_password));
    ck_assert(account_validate_password(acc, special_password));
    
    account_free(acc);

/* Password complexity tests */
}
END_TEST

START_TEST(password_complexity_requirements)
{
#line 182
    account_t* acc = create_test_account();
    
    /* Too short */
    ck_assert(!account_update_password(acc, "Sh0rt!"));
    
    /* No diversity (only lowercase) */
    ck_assert(!account_update_password(acc, "abcdefghijkl"));
    
    /* No diversity (only uppercase) */
    ck_assert(!account_update_password(acc, "ABCDEFGHIJKL"));
    
    /* No diversity (only numbers) */
    ck_assert(!account_update_password(acc, "12345678901"));
    
    /* Borderline acceptable (3 char types) */
    ck_assert(account_update_password(acc, "Password123"));
    
    account_free(acc);

}
END_TEST

START_TEST(multiple_password_updates)
{
#line 202
    account_t* acc = create_test_account();
    
    /* Multiple updates in sequence */
    for (int i = 0; i < 10; i++) {
        char password[20];
        snprintf(password, sizeof(password), "P@ssw0rd%d!", i);
        ck_assert(account_update_password(acc, password));
        ck_assert(account_validate_password(acc, password));
    }
    
    account_free(acc);

}
END_TEST

START_TEST(update_resets_failure_count)
{
#line 215
    account_t* acc = create_test_account();
    
    /* Record failed login attempts */
    for (int i = 0; i < 5; i++) {
        account_record_login_failure(acc);
    }
    
    ck_assert_int_eq(acc->login_fail_count, 5);
    
    /* Update password should reset failure count */
    ck_assert(account_update_password(acc, "NewP@ssw0rd!"));
    ck_assert_int_eq(acc->login_fail_count, 0);
    
    account_free(acc);

/*********************************************
 * Tests for account_is_banned
 *********************************************/
}
END_TEST

#line 235
/* Basic functionality tests */
START_TEST(fresh_account_not_banned)
{
#line 237
    account_t* acc = create_test_account();
    ck_assert(!account_is_banned(acc));
    account_free(acc);

}
END_TEST

START_TEST(account_banned_with_future_unban_time)
{
#line 242
    account_t* acc = create_test_account();
    time_t future_time = time(NULL) + 3600; /* One hour in the future */
    account_set_unban_time(acc, future_time);
    ck_assert(account_is_banned(acc));
    account_free(acc);

}
END_TEST

START_TEST(account_not_banned_with_past_unban_time)
{
#line 249
    account_t* acc = create_test_account();
    time_t past_time = time(NULL) - 3600; /* One hour in the past */
    account_set_unban_time(acc, past_time);
    ck_assert(!account_is_banned(acc));
    account_free(acc);

/* Edge cases */
}
END_TEST

START_TEST(null_parameter_banned)
{
#line 257
    ck_assert(!account_is_banned(NULL));

}
END_TEST

START_TEST(zero_unban_time_not_banned)
{
#line 260
    account_t* acc = create_test_account();
    acc->unban_time = 0;
    ck_assert(!account_is_banned(acc));
    account_free(acc);

}
END_TEST

START_TEST(max_time_banned)
{
#line 266
    account_t* acc = create_test_account();
    acc->unban_time = LONG_MAX;  /* Far future */
    ck_assert(account_is_banned(acc));
    account_free(acc);

}
END_TEST

START_TEST(negative_time_banned)
{
#line 272
    account_t* acc = create_test_account();
    acc->unban_time = -1;  /* In the past */
    ck_assert(!account_is_banned(acc));
    account_free(acc);

}
END_TEST

START_TEST(time_manipulation)
{
#line 278
    account_t* acc = create_test_account();
    
    /* Ban for 10 seconds */
    time_t current = time(NULL);
    account_set_unban_time(acc, current + 10);
    
    /* Should be banned */
    ck_assert(account_is_banned(acc));
    
    /* Unban */
    account_set_unban_time(acc, 0);
    ck_assert(!account_is_banned(acc));
    
    /* Ban and then unban */
    account_set_unban_time(acc, current + 3600);
    ck_assert(account_is_banned(acc));
    account_set_unban_time(acc, 0);
    ck_assert(!account_is_banned(acc));
    
    account_free(acc);

/*********************************************
 * Tests for account_is_expired
 *********************************************/
}
END_TEST

#line 304
/* Basic functionality tests */
START_TEST(fresh_account_not_expired)
{
#line 306
    account_t* acc = create_test_account();
    ck_assert(!account_is_expired(acc));
    account_free(acc);

}
END_TEST

START_TEST(account_not_expired_with_future_time)
{
#line 311
    account_t* acc = create_test_account();
    time_t future_time = time(NULL) + 3600; /* One hour in the future */
    account_set_expiration_time(acc, future_time);
    ck_assert(!account_is_expired(acc));
    account_free(acc);

}
END_TEST

START_TEST(account_expired_with_past_time)
{
#line 318
    account_t* acc = create_test_account();
    time_t past_time = time(NULL) - 3600; /* One hour in the past */
    account_set_expiration_time(acc, past_time);
    ck_assert(account_is_expired(acc));
    account_free(acc);

/* Edge cases */
}
END_TEST

START_TEST(null_parameter_expired)
{
#line 326
    ck_assert(!account_is_expired(NULL));

}
END_TEST

START_TEST(zero_expiration_time_not_expired)
{
#line 329
    account_t* acc = create_test_account();
    acc->expiration_time = 0;
    ck_assert(!account_is_expired(acc));
    account_free(acc);

}
END_TEST

START_TEST(max_time_not_expired)
{
#line 335
    account_t* acc = create_test_account();
    acc->expiration_time = LONG_MAX;  /* Far future */
    ck_assert(!account_is_expired(acc));
    account_free(acc);

}
END_TEST

START_TEST(current_time_is_expired)
{
#line 341
    account_t* acc = create_test_account();
    time_t current = time(NULL);
    account_set_expiration_time(acc, current);
    ck_assert(account_is_expired(acc));
    account_free(acc);

}
END_TEST

START_TEST(negative_time_expired)
{
#line 348
    account_t* acc = create_test_account();
    acc->expiration_time = -1;  /* In the past */
    ck_assert(account_is_expired(acc));
    account_free(acc);

/*********************************************
 * Interaction tests
 *********************************************/
}
END_TEST

START_TEST(banned_and_expired_interaction)
{
#line 359
    account_t* acc = create_test_account();
    
    /* Set both ban and expiration */
    time_t current = time(NULL);
    time_t future_ban = current + 3600; /* Future ban */
    time_t past_expiration = current - 3600; /* Past expiration */
    
    account_set_unban_time(acc, future_ban);
    account_set_expiration_time(acc, past_expiration);
    
    /* Account should be both banned and expired */
    ck_assert(account_is_banned(acc));
    ck_assert(account_is_expired(acc));
    
    /* Password validation should fail */
    ck_assert(!account_validate_password(acc, "TestP@ss123"));
    
    account_free(acc);

}
END_TEST

START_TEST(failure_count_affects_validation)
{
#line 379
    account_t* acc = create_test_account();
    
    /* Record many failed login attempts */
    for (int i = 0; i < 10; i++) {
        account_record_login_failure(acc);
    }
    
    /* Should be rate-limited now */
    ck_assert(!account_validate_password(acc, "TestP@ss123"));
    
    /* Updating password should reset failure count */
    ck_assert(account_update_password(acc, "NewP@ssw0rd!"));
    ck_assert_int_eq(acc->login_fail_count, 0);
    
    /* Should be able to validate now */
    ck_assert(account_validate_password(acc, "NewP@ssw0rd!"));
    
    account_free(acc);
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("account_suite");
    TCase *tc1_1 = tcase_create("password_validation_tests");
    TCase *tc1_2 = tcase_create("password_update_tests");
    TCase *tc1_3 = tcase_create("account_banned_tests");
    TCase *tc1_4 = tcase_create("account_expired_tests");
    TCase *tc1_5 = tcase_create("account_interaction_tests");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, valid_password_succeeds);
    tcase_add_test(tc1_1, invalid_password_fails);
    tcase_add_test(tc1_1, null_parameters);
    tcase_add_test(tc1_1, empty_password);
    tcase_add_test(tc1_1, very_long_password);
    tcase_add_test(tc1_1, special_characters_in_password);
    tcase_add_test(tc1_1, account_with_no_password_hash);
    tcase_add_test(tc1_1, banned_account_validation);
    tcase_add_test(tc1_1, expired_account_validation);
    suite_add_tcase(s1, tc1_2);
    tcase_add_test(tc1_2, update_valid_password);
    tcase_add_test(tc1_2, null_parameters_update);
    tcase_add_test(tc1_2, empty_password_update);
    tcase_add_test(tc1_2, very_long_password_update);
    tcase_add_test(tc1_2, special_characters_password_update);
    tcase_add_test(tc1_2, password_complexity_requirements);
    tcase_add_test(tc1_2, multiple_password_updates);
    tcase_add_test(tc1_2, update_resets_failure_count);
    suite_add_tcase(s1, tc1_3);
    tcase_add_test(tc1_3, fresh_account_not_banned);
    tcase_add_test(tc1_3, account_banned_with_future_unban_time);
    tcase_add_test(tc1_3, account_not_banned_with_past_unban_time);
    tcase_add_test(tc1_3, null_parameter_banned);
    tcase_add_test(tc1_3, zero_unban_time_not_banned);
    tcase_add_test(tc1_3, max_time_banned);
    tcase_add_test(tc1_3, negative_time_banned);
    tcase_add_test(tc1_3, time_manipulation);
    suite_add_tcase(s1, tc1_4);
    tcase_add_test(tc1_4, fresh_account_not_expired);
    tcase_add_test(tc1_4, account_not_expired_with_future_time);
    tcase_add_test(tc1_4, account_expired_with_past_time);
    tcase_add_test(tc1_4, null_parameter_expired);
    tcase_add_test(tc1_4, zero_expiration_time_not_expired);
    tcase_add_test(tc1_4, max_time_not_expired);
    tcase_add_test(tc1_4, current_time_is_expired);
    tcase_add_test(tc1_4, negative_time_expired);
    suite_add_tcase(s1, tc1_5);
    tcase_add_test(tc1_5, banned_and_expired_interaction);
    tcase_add_test(tc1_5, failure_count_affects_validation);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
